Running Java benchmark MGopt, class D, on 4 servers (np=4), tcp,self

Servers:
mpi002
mpi003
mpi025
mpi026

mpirun --mca btl tcp,self --bind-to core --map-by node -np 4 java NPB_MPJ.MGopt class=D

Start: Mon Feb 17 11:58:22 PST 2014
===============================================================================
Exception in thread "main" java.lang.NegativeArraySizeException
	at NPB_MPJ.MGopt.runBenchmark(MGopt.java:198)
Exception in thread "main" java.lang.NegativeArraySizeException
	at NPB_MPJ.MGopt.main(MGopt.java:113)	at NPB_MPJ.MGopt.runBenchmark(MGopt.java:198)
	at NPB_MPJ.MGopt.main(MGopt.java:113)

Exception in thread "main" java.lang.NegativeArraySizeException
	at NPB_MPJ.MGopt.runBenchmark(MGopt.java:198)
	at NPB_MPJ.MGopt.main(MGopt.java:113)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
Exception in thread "main" java.lang.NegativeArraySizeException
	at NPB_MPJ.MGopt.runBenchmark(MGopt.java:198)
	at NPB_MPJ.MGopt.main(MGopt.java:113)
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[2426,1],2]
  Exit code:    1
--------------------------------------------------------------------------
===============================================================================
End: Mon Feb 17 11:58:24 PST 2014
